const types = {
  CREATESAFE: "CREATESAFE",
  EDITSAFE: "EDITSAFE",
  DELETE_SAFE: "DELETE_SAFE",
  SELECTED_SAFE: "SELECTED_SAFE",
  CREATESECRET: "CREATESECRET",
  ADDFOLDER: "ADDFOLDER",
  CREATESAFEINFOL: "CREATESAFEINFOL",
  DELETESAFEINFOL: "DELETESAFEINFOL",
};

export default types;
